version: "3.9"

services:
  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/rails
      - ~/.ssh:/home/rails/.ssh:ro
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
    entrypoint: ./entrypoints/web.sh

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata: